export default [
    { meta: { title: '栅格' }, path: '/grid', component: () => import("./views/grid") },
    { meta: { title: '段落' }, path: '/paragraph', component: () => import("./views/paragraph") },
    { meta: { title: '顶部导航' }, path: '/navbar', component: () => import("./views/navbar") },
    { meta: { title: '底部导航' }, path: '/tabbar', component: () => import("./views/tabbar") },
    { meta: { title: '导航' }, path: '/nav', component: () => import("./views/nav") },

    { meta: { title: '图标' }, path: '/icon', component: () => import("./views/icon") },
    { meta: { title: '按钮' }, path: '/button', component: () => import("./views/button") },
    { meta: { title: '进度' }, path: '/progress', component: () => import("./views/progress") },
    { meta: { title: '标签' }, path: '/tag', component: () => import("./views/tag") },
    { meta: { title: '面包屑' }, path: '/bread', component: () => import("./views/bread") },
    { meta: { title: '图片' }, path: '/img', component: () => import("./views/img") },
    // { meta: { title: '多级标题' }, path: '/title', component: () => import("./views/button") },
    { meta: { title: '分割线' }, path: '/hr', component: () => import("./views/hr") },

    { meta: { title: '输入框' }, path: '/input', component: () => import("./views/input") },
    { meta: { title: '选择器' }, path: '/select', component: () => import("./views/select") },
    { meta: { title: '单选' }, path: '/radio', component: () => import("./views/radio") },
    { meta: { title: '多选' }, path: '/checkbox', component: () => import("./views/checkbox") },
    { meta: { title: '开关' }, path: '/switch', component: () => import("./views/switch") },

    { meta: { title: '过渡' }, path: '/transition', component: () => import("./views/transition") },
    { meta: { title: '遮罩' }, path: '/mask', component: () => import("./views/mask") },
    { meta: { title: '吐司' }, path: '/toast', component: () => import("./views/toast") },
    { meta: { title: '弹出层' }, path: '/popup', component: () => import("./views/popup") },
    { meta: { title: '提示' }, path: '/tip', component: () => import("./views/tip") },
    { meta: { title: '加载' }, path: '/loading', component: () => import("./views/loading") },
    // { meta: { title: '确认' }, path: '/confirm', component: () => import("./views/confirm") },
    // { meta: { title: '模态框' }, path: '/modal', component: () => import("./views/modal") },
    // { meta: { title: '滚动监听' }, path: '/scrollspy', component: () => import("./views/scrollspy") },
    // { meta: { title: '钉' }, path: '/pin', component: () => import("./views/pin") },
    // { meta: { title: '回到顶部' }, path: '/top', component: () => import("./views/top") },
    { meta: { title: '分页' }, path: '/page', component: () => import("./views/page") },
    { meta: { title: '轮播' }, path: '/sliderbox', component: () => import("./views/sliderbox") },

]